name: teamproject
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  kakao_flutter_sdk_user: ^1.1.1
  kakao_flutter_sdk: ^1.0.0 # 최신 버전으로 업데이트
  shared_preferences: ^2.0.0
  flutter_local_notifications: ^9.3.3
  path_provider: ^2.0.9
  intl: ^0.17.0
  pull_to_refresh: ^2.0.0
  table_calendar: ^3.0.0
  provider: ^6.0.0
  geolocator: ^8.0.0
  uuid: ^3.0.4
  url_launcher: ^6.0.9
  timezone:
  image_picker:



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  intl: ^0.17.0
  pull_to_refresh: ^2.0.0
  table_calendar: ^3.0.0


flutter:
  fonts:
    - family: 210 Ojunohwhoo L
      fonts:
        - asset: lib/예쁜글씨체/210 Ojunohwhoo L.ttf
    - family: 210 시골밥상L
      fonts:
        - asset: lib/예쁜글씨체/210 시골밥상L.ttf
    - family: HGSS
      fonts:
        - asset: lib/예쁜글씨체/HGSS.ttf
    - family: HoonSlimskinnyL
      fonts:
        - asset: lib/예쁜글씨체/HoonSlimskinnyL.ttf
    - family: SangSangFlowerRoad
      fonts:
        - asset: lib/예쁜글씨체/SangSangFlowerRoad.otf
    - family: SangSangShinb7.
      fonts:
        - asset: lib/예쁜글씨체/SangSangShinb7.otf
    - family: THE블랙잭L
      fonts:
        - asset: lib/예쁜글씨체/THE블랙잭L.ttf
    - family: tvN Enjoystories Light
      fonts:
        - asset: lib/예쁜글씨체/tvN Enjoystories Light.ttf
    - family: Typo_CrayonM
      fonts:
        - asset: lib/예쁜글씨체/Typo_CrayonM.ttf
    - family: Typo_TodayWeatherM
      fonts:
        - asset: lib/예쁜글씨체/Typo_TodayWeatherM.ttf

  uses-material-design: true

assets:
  - lib/memo/diaries.json

permissions:
  - read_external_storage
  - write_external_storage
